### ISSUE TITLE
This is cheating

### ISSUE THREAD

**Issue by gokhalevedant06** [Manomay15/AI#1]
![image](https://user-images.githubusercontent.com/79954118/203858473-62272d52-3b1a-473b-ac12-1152016e6c79.png)

**Comment by gokhalevedant06** [comment]
@Manomay15 What is this behaviour

**Comment by AtharvKinage** [comment]
@Manomay15 please assign this issue to me.

**Comment by Adw8** [comment]
@Manomay15 how could you do this, unsubscribing >:(

**Comment by Manomay15** [comment]
Relax guys, it's just an open source contribution
